### PR TITLE
Support Human Entity

### PR DESCRIPTION
**Pull request by kaxyum**
## Introduction
When we register a human entity it crashes

## Changes
```CustomiesEntityFactory->registerEntity``` has been changed to support human entity

### CODE REVIEW

**Comment by IvanCraft623** [comment]
You don't need Customies to register a Human entity, just do it with the native PM API

**Comment by kaxyum** [comment]
> You don't need Customies to register a Human entity, just do it with the native PM API

So what's the point of registering entities with customies?

**Comment by TwistedAsylumMC** [comment]
This change is actually not necessary to support human entities. You can pass in your own creationfunc to the register function to override customies default behaviour.
```php
registerEntity(CustomHuman::class, "customies:custom_human", static function (World $world, CompoundTag $nbt): Entity {
    return new CustomHuman(EntityDataHelper::parseLocation($nbt, $world), Human::parseSkinNBT($nbt), $nbt);
});
```

**Comment by kaxyum** [comment]
so it's useless to register entities with customies , so delete this function

**Comment by TwistedAsylumMC** [comment]
It's not, because custom entitiy identifiers need to be sent in the AvailableActorIdentifiersPacket. I guess it could be simplified down to a "registerEntityIdentifier", but the current method just makes it slightly easier and more simple for people to register entities. I appreciate the pull request, but like I mentioned it can be done with the current method already

**Comment by kaxyum** [comment]
You also need to simplify the registration of human entities.

**Pull request closed without merging**
