### PR TITLE
Add shooter component for items

### PR DESCRIPTION
**Pull request by xLordShadow**
This adds the shooting component type for items, allows you tell when a user is charging an item and when they stop. 

This kind of component wasnt added and I needed it so I added it in. Please let me know if any changes are needed.

### CODE REVIEW

**Comment by unickorn** [comment]
Does this work without the ammunition field? How does it even know what to shoot?

**Comment by xLordShadow** [comment]
Yes it works without the ammunition field.

If you want it to actually shoot something I suggest using pmmps bow code to see how it could shoot. 
Without this component, the client cannot detect the charging system from the item. (Holding right click)
The ammunition field by default is set to arrow but that dosnt mean you have to have arrows to right click the item.

**Comment by unickorn** [comment]
Does PM have a way of blocking the client from holding right click if they don't have the desired ammunition? If I want a custom bow item to shoot arrows, is it possible to prevent the charging effect with this PR?

If not that is also fine (at least in my opinion), but maybe including what is missing in the TODO will make things easier to fix in the future.

**Comment by xLordShadow** [comment]
Im not sure, without this component there is no right clicking at all so im assuming not.

For my purpose im using.. guns. They right click and Im able to tell they right clicked with the PlayerItemUseEvent then in the item class itself I say to stop shooting in "onReleaseUsing".

So im assuming by cancelling the PlayerItemUseEvent you can block them from charging an item.

**Comment by xLordShadow** [comment]
The point of this PR is to add the ability to create items that are chargeable. Im not trying to write everyones code for their own chargeable items. If Seb dosnt want to merge this because of it.. then oh well.

**Comment by TwistedAsylumMC** [comment]
I'm okay with this PR, but I feel like the ammunition field should be implemented otherwise there may be unexpected behaviour when using custom ammunition. The other thing is are all the fields actually necessary? They all just look like they are for the behaviour pack to implement the weapon and not actually have any client side functionality. Would you mind testing without each field and see if they are necessary?

**Review by xLordShadow — COMMENTED** [review]
This should not be on this pull request.. wish it pushed it to mine version instead.

**Comment by xLordShadow** [comment]
Ive added the brief and useless descriptions given on the documentation. Also I tried changing the values up to see if anything changes. 

From my knowledge they had no effect on what was happening in-game. Probably since PMMP dosnt care about the items information when it comes to force/power because they determine that based on server tick and time spent holding. Keep in mind this component is for the bow and trident. 

Without this component, the client never sends a packet when they stop using an item. Pocketmine listens and responds to the onReleaseUsing function in the item class.

**Pull request closed without merging**
