### PR TITLE
Composer

### PR DESCRIPTION
**Pull request by xxAROX**
#25

### CODE REVIEW

**Comment by sebfayers** [comment]
Customies will not work with composer, there needs to be one global instance only per server, so a per plugin version will cause issues

**Comment by xxAROX** [comment]
for api stuff like plugins that require customies

**Comment by xxAROX** [comment]
not to built in plugin

**Comment by xxAROX** [comment]
only for IDE stuff like autocompletions
grafik

**Comment by xxAROX** [comment]
like the screenshot

**Comment by xxAROX** [comment]
thats why the issue(#25 ) called "**for dev**"

**Comment by TwistedAsylumMC** [comment]
You do not need composer to achieve this. You can add the source or the phar via phpstorm in the settings. [PHPStorm Include Paths](https://www.jetbrains.com/help/phpstorm/configuring-include-paths.html)

**Comment by xxAROX** [comment]
i prefer it to manage my required "packages"/plugins via composer with repositories because its much cleaner instead of searching and scrolling in my included paths 👌

**Comment by xxAROX** [comment]
its not my decision ik

**Pull request closed without merging**
