### PR TITLE
Allow passing ListTag components as array with mixed types

### PR DESCRIPTION
**Pull request by Refaltor77**

### CODE REVIEW

**Comment by ScarceityPvP** [comment]
what’s the reason for this pr?

**Comment by Unickorn** [comment]
Possibly to allow an array of mixed types to be passed, but it could be done a bit cleaner with something recursive imo.

**Comment by Refaltor77** [comment]
Yes that’s exactly it, I had a value type concern so I tinker with this little patch to create what I needed

**Review by Unickorn — CHANGES_REQUESTED** [review]
The indents seem to be broken, please fix that!

**Comment by TwistedAsylumMC** [comment]
I'll close this issue due to inactivity and a new PR which aims to solve the same issue (https://github.com/CustomiesDevs/Customies/pull/46). Thanks for the solution to this problem!

**Pull request closed without merging**
